Show login as first view on desktop startup
withspectrum/spectrum pull request #3198
Opened 2018-05-30 12:32 UTC by mxstbr

**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)
- desktop

2018-05-30 14:10 UTC, brianlovin requested changes
This leaves a fairly bad flashing white screen when the app starts - do you notice this as well? Ideally we can have the fallback not flash anything - perhaps a loading screen to decide whether to show the inbox or login view first.

2018-05-31 09:46 UTC, mxstbr commented
Hmm, not sure I'm seeing that. Gimme some repro steps?

2018-05-31 17:38 UTC, brianlovin commented
> Hmm, not sure I'm seeing that. Gimme some repro steps?

Ah, it's a problem if you log out, quit the app, then reopen the app. Going to create another issue for this actually because the bug here is that if you log out and then quit the app, then restart the app, you'll be logged back in (at which point it flashes the login screen)

So this PR is good to go

2018-05-31 17:38 UTC, brianlovin approved these changes

2018-05-31 18:15 UTC, merged