Format online counts to locale
withspectrum/spectrum pull request #4384
Opened 2018-11-30 23:10 UTC by brianlovin

**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

2018-12-01 11:30 UTC, mxstbr requested changes
Let's make sure to do `Number(...).toLocaleString()` in case the count isn't returned correctly from the server so it doesn't crash.

2018-12-01 19:40 UTC, PierreAndreis commented on src/components/profile/community.js
> +                    {community.metaData.onlineMembers.toLocaleString()} online
```suggestion
                   {Number(community.metaData.onlineMembers).toLocaleString()} online
```

2018-12-01 19:40 UTC, PierreAndreis commented on src/views/channel/index.js
> +                      {channel.metaData.onlineMembers.toLocaleString()} online
```suggestion
                      {Number(channel.metaData.onlineMembers).toLocaleString()} online
```

2018-12-01 23:40 UTC, brianlovin commented
> Let's make sure to do Number(...).toLocaleString() in case the count isn't returned correctly from the server so it doesn't crash.

2018-12-02 11:56 UTC, innnzzz6 commented on src/views/channel/index.js
> +                      {channel.metaData.onlineMembers.toLocaleString()} online
425

2018-12-02 11:56 UTC, innnzzz6 commented on src/components/profile/community.js
> +                    {community.metaData.onlineMembers.toLocaleString()} online
190

2018-12-04 01:10 UTC, brianlovin commented
Ping @mxstbr

2018-12-04 08:05 UTC, mxstbr approved these changes
Okay okay you smartass... 😜

2018-12-04 08:06 UTC, merged