Add info tab to channels on mobile
withspectrum/spectrum pull request #4951
Opened 2019-03-24 10:48 UTC by mxstbr

**Status**
- [ ] WIP
- [x] Ready for review
- [ ] Needs testing

**Deploy after merge (delete what needn't be deployed)**
- hyperion (frontend)

2019-03-24 10:50 UTC, brianlovin requested changes
We should copy some of the same logic from community info tab to leave the channel and go to settings if you have permissions

2019-03-24 13:33 UTC, mxstbr commented
I am not sure what that means, this is the exact same code we use for the desktop sidebar.

2019-03-26 20:23 UTC, brianlovin commented
This is fine for now, I'll do another pass on info tabs later

2019-03-26 20:23 UTC, brianlovin approved these changes

2019-03-26 20:23 UTC, merged